# Exclude any file that appears to be input data
exclude: '^.*/day.*\.txt$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --line-length=70
          - --preview
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.0"
    hooks:
      - id: mypy
        name: checking types with mypy
        args:
          - --strict
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: day1-part1-check
        name: checking day1-part1
        language: system
        entry: ./day1/day1-part1.py
        files: ^day1/.*$
      - id: day1-part2-check
        name: checking day1-part2
        language: system
        entry: ./day1/day1-part2.py
        files: ^day1/.*$
      - id: day1-part2b-check
        name: checking day1-part2b
        language: system
        entry: ./day1/day1-part2b.py
        files: ^day1/.*$
      - id: day2-check
        name: checking day2
        language: system
        entry: ./day2/day2.py
        files: ^day2/.*$
      - id: day3-check
        name: checking day3
        language: system
        entry: ./day3/day3.py
        files: ^day3/.*$
      - id: day4-check
        name: checking day4
        language: system
        entry: ./day4/day4.py
        files: ^day4/.*$
      - id: day5-check
        name: checking day5
        language: system
        entry: ./day5/day5.py
        files: ^day5/.*$
      - id: day6-check
        name: checking day6
        language: system
        entry: ./day6/day6.py
        files: ^day6/.*$
      - id: day7-check
        name: checking day7
        language: system
        entry: ./day7/day7.py
        files: ^day7/.*$
      - id: day8-check
        name: checking day8
        language: system
        entry: ./day8/day8.py
        files: ^day8/.*$
      - id: day9-check
        name: checking day9
        language: system
        entry: ./day9/day9.py
        files: ^day9/.*$
      - id: day10-check
        name: checking day10
        language: system
        entry: ./day10/day10.py
        files: ^day10/.*$
      - id: day11-check
        name: checking day11
        language: system
        entry: ./day11/day11.py
        files: ^day11/.*$
      - id: day-12-check
        name: checking day12
        language: system
        entry: ./day12/day12.py
        files: ^day12/.*$
      - id: day-13-check
        name: checking day13
        language: system
        entry: ./day13/day13.py
        files: ^day13/.*$
      - id: day14-check
        name: checking day14
        language: system
        entry: ./day14/day14.py
        files: ^day14/.*$
      - id: day15-check
        name: checking day15
        language: system
        entry: ./day15/day15.py
        files: ^day15/.*$
      - id: day16-check
        name: checking day16
        language: system
        entry: ./day16/day16.py
        files: ^day16/.*$
      - id: day18-check
        name: checking day18
        language: system
        entry: ./day18/day18.py
        files: ^day18/.*$
      - id: day19-check
        name: checking day19
        language: system
        entry: ./day19/day19.py
        files: ^day19/.*$
      - id: day20-check
        name: checking day20
        language: system
        entry: ./day20/day20.py
        files: ^day20/.*$
      - id: day20-tests
        name: running tests for day20
        language: system
        entry: pytest ./day20
        files: ^day20/.*$
      - id: day21-check
        name: checking day21
        language: system
        entry: ./day21/day21.py
        files: ^day21/.*$
      - id: day23-check
        name: checking day23
        language: system
        entry: ./day23/day23.py
