# Exclude any file that appears to be input data
exclude: '^.*/day.*\.txt$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --line-length=70
          - --preview
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.0"
    hooks:
      - id: mypy
        name: checking types with mypy
  - repo: local
    hooks:
      - id: day1-part1-check
        name: checking day1-part1
        language: system
        entry: ./day1/day1-part1.py
      - id: day1-part2-check
        name: checking day1-part2
        language: system
        entry: ./day1/day1-part2.py
      - id: day1-part2b-check
        name: checking day1-part2b
        language: system
        entry: ./day1/day1-part2b.py
      - id: day2-check
        name: checking day2
        language: system
        entry: ./day2/day2.py
      - id: day3-check
        name: checking day3
        language: system
        entry: ./day3/day3.py
