name: Docs

on:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: "Build Documentation"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Pre-build devcontainer image
        uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
        with:
          imageName: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          cacheFrom: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          push: always
      - name: Build docs
        uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
        with:
          push: never
          imageName: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          runCmd: |
            cd docs
            yarn install --frozen-lockfile
            yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1