name: Pre-Commit

on:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: write

jobs:
  run-pre-commit:
    name: "Run pre-commit"
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pre-build devcontainer image
        uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
        with:
          imageName: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          cacheFrom: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          push: always
      - name: Run pre-commit
        uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
        with:
          push: never
          imageName: ghcr.io/kbalston/advent-of-code-2022-devcontainer
          runCmd: |
            pre-commit run --all
